version: '3.7'

services:
  user-service:
    image : user:latest
    ports:
      - "8085:8085"
  advertiser-service:
    image : advertiser:latest
    ports:
      - "8083:8083"
  gateway:
    depends_on:
      - user-service
      - advertiser-service
    image : gateway:latest
    restart: always
    ports:
      - "8090:8090"
    environment:
      USER_SERVICE_URL: http://localhost:8085
      ADVERTISER_SERVICE_URL: http://localhost:8083
  front:
    depends_on:
      - gateway
    image: fronturba:latest
    restart: always
    ports:
      - "8080:80"
    links:
      - gateway